travis:
  secure:
    BINSTAR_TOKEN: REdCPj1P3st1NTs07RBc9LaR7uqLzQHX5Vu83sd8i8zYgMcBfKRnKLKNM/md2TYr5Z1m+ngY8016WBptxgq+k9fVRc4GgFUdSnCoY/K1lwr49ibsD03hQSSRDzdAeZgSBQb+eLVXWxwcZlDgxgcYDqxLVbsIvlkPe67y0PGbDxeqQogRWWHmuis0ciHiAIPJG8lNrY4rd+E4xHMSBVlTN2W66eli4LX9SxrPiF9mVG2SCEXj951+A8shNC+kEvzPPWW4pFpYD7bSN77msm47LgZc95M+niVWrP8WQ27BGa4Ix1RRZJFvs5QoyWDnnF8oLCqQP+YNdnyOP4rRprw7NbOBp1/UlKAkgL1XVpJ3yi13Q0mKwZfCWGNJ/efZZSFtdrvZyv1yVfttZIqGgXujynDZtPFfVn+t48JpXGFPyA/LMT4ZiLnWHEnLPKvEqlz7CsryD/6S6u5PuNwXmjphlP/gA+yT1muUlWYK9PR09bt2547vTLwYhPOVE8OAsCqJjj/hw8Mf4jaX7MftV9KgiSWmhbQzlxgKZwW3NM0FeMrPaU4qY0Lsn+XgAysNI9xSd/wTImsBzWCasniS36f0IviaVMUyz3Js2JsYd7OKFJye4yimZi/C4Lfu0ve9SfGNb0PTmRq2p55CJi4feZNwI+SIrIqTHj9BoOAAzS7cn6E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
